### ISSUE TITLE
Reduced Row Echelon Form Bug

### ISSUE THREAD

**Issue by KayakDov** [lessthanoptimal/ejml#115]
The following code does not yield reduced row echelon form.

DMatrixRMaj matrix = new DMatrixRMaj(2, 3, true, new double[]{0,2,2,0,0,2});
System.out.println(CommonOps_DDRM.rref(matrix, -1, null));

Prints:
Type = DDRM , rows = 2 , cols = 3
 0.0000E+00  1.0000E+00  1.0000E+00 
 0.0000E+00  0.0000E+00  2.0000E+00 

but the first non zero element on each row should be 1.

**Comment by lessthanoptimal** [comment]
Thanks for bringing this up, but the behavior you see appears to be correct since the columns are all zeros. I doubled checked by comparing it against Octave:

```octave:1> A=[0 2 2;0 0 2]
A =

   0   2   2
   0   0   2

octave:2> rref(A)
ans =

   0   1   0
   0   0   1
```

This is a good unit test, so I've added it to EJML. Let me know if you have any additional thoughts. Also sorry for the log delay in looking into this simple issue.

**Comment by lessthanoptimal** [comment]
Deleted first reply since I can't apparently read. Looking into this.

**Comment by lessthanoptimal** [comment]
Fixed the issue. Combination of bad test coverage of bad default value for number of columns. Thanks for pointing out the problem. I'm surprised this went unnoticed for so long!

https://github.com/lessthanoptimal/ejml/pull/130

Also apologies for taking so long to look into this and missing it in the last release.
