### ISSUE TITLE
SimpleMatrix.invert() produces incorrect result for a particular 29x29 matrix

### ISSUE THREAD

**Issue by AlanBMatthews** [lessthanoptimal/ejml#153]
A non singular 29 x 29 matrix(Frame Stiffness) that has been produced by an engineering program I am writing produces an incorrect answer when I attempt to invert it using SimpleMatrix.invert(). Open Office LibreCalc successfully inverts the matrix as the matrix product of itself and its inverse (M x M<sup>-1</sup>) produces the identity matrix. Attached are the ODS and CSV files of the output. The sheets in the Stiffness.ODS file marked as (cleaned) are simply very small values that are almost zero replaced with zero to aid comparisons between the various sheets
[InvStiffness.CSV](https://github.com/lessthanoptimal/ejml/files/8986901/InvStiffness.CSV)
[Stiffness.CSV](https://github.com/lessthanoptimal/ejml/files/8986902/Stiffness.CSV)
[Stiffness.ods](https://github.com/lessthanoptimal/ejml/files/8986903/Stiffness.ods)
.

**Comment by lessthanoptimal** [comment]
Sorry for the slow response.

Stiffness.ods appears to be singular, which is why inverting it is an issue.

Stiffness.CSV isn't singular but it's getting there. I've done some testing using octave:
`min(svd(a)) == 0.000029395`

Inverting it in Octave and BoofCV work, but they both have accuracy issues. I'm finding the largest difference between a*inv(a) and the identity matrix:
`max((a*inv(a) - eye(size(a)))(:)) == 0.032590`

Then in EJML

`s.mult(s.invert()).minus(SimpleMatrix.identity(a.numRows)).elementMaxAbs()) ==  4.76837158203125E-7`
where 's' is a SimpleMatrix.

Right now it looks like the results are reasonable. Does this analysis seem reasonable?

**Comment by AlanBMatthews** [comment]
Thanks for that Peter. I'm suspecting that the problem lies with my inserting nodes in my frame network which are very close to existing ones which is probably causing the resulting stiffness matrix to be ill-conditioned.
