### ISSUE TITLE
Java 19 SIMD support for matrix operations ?

### ISSUE THREAD

**Issue by eix128** [lessthanoptimal/ejml#169]
Hi java 19 has released simd vector support.Its the fastest computation library that translates java code into native MMX , SSE or AVX512 codes.

IT would be good to add this support to this matrix library.

You can look at examples:
https://medium.com/@Styp/java-18-vector-api-do-we-get-free-speed-up-c4510eda50d2

Simple SIMD Example:
https://vksegfault.github.io/posts/java-simd/

Very good example to used advanced features : 
https://www.morling.dev/blog/fizzbuzz-simd-style/

Youtube video:
https://www.youtube.com/watch?v=VYo3p4R66N8

**Comment by lessthanoptimal** [comment]
Still want to work on this, but don't have time right now. My current projects are bound by sparse performance not dense. If someone wants to give it a shot I will do my best to help them. Closing this ticket since there's a very similar one from you already.

https://github.com/lessthanoptimal/ejml/issues/142
