### ISSUE TITLE
complexity order of mult and inverse method 

### ISSUE THREAD

**Issue by master2015** [lessthanoptimal/ejml#21]
hello

I am writing a paper using mult and inverse method in ejml library.
I want to know the complexity  order of these methods for my paper. would you please help me?

I calculated the time of these methods in my paper. but i could not get complexity order for these methods.
I means o(n,..n^2,....)?

Thanks

**Comment by lessthanoptimal** [comment]
For a N by N matrix the time complexities are:

O(N^3) = matrix multiplication
O(N^3) = LU decomposition based matrix inverse

You might find this stackoverflow question interesting since the above equations are a bit of a simplification.  In practice the constant terms are important, e.g. unless the matrix is huge, a O(N^3) algorithm will be faster than a O(N^2.237) algorithm.  Probably not relevant for your paper...

https://math.stackexchange.com/questions/1330759/time-complexity-of-lu-decomposition

**Comment by master2015** [comment]
So, EJML  library implemented o(n^3) for matrix multiplication not Strasen algorithm ?
I have another question.
if I want to calculate unknown matrices in matrix multiplication should product each direction of multiply in inverted matrix in ejml ? would you please write sodo code for this in ejml ?
i mean A*X=B
(A,X,B are square matrix n*n)

**Comment by lessthanoptimal** [comment]
Correct.  You're unlikely to use Strasen.  It has to be a very large matrix to overcome the O(N^3) techniques and has numerical stability issues, from what I have read.

Could you reword the sentence that starts with "if I want to calculate..." ?  I'm having trouble understanding what you're asking for.

**Comment by master2015** [comment]
which method in EJML  you propose for finding unknown matrices in matrix multiplication.

A*X=B
The goal is to find X matrix . (A,X,B are Square Matrices  -- 4*4 or 5*5,.....)
I think for finding it, we should product each side of equation in inverted A .Shall we?

A*A^-1 *X= A^-1 *B
would you write code for this?

thanks

**Comment by lessthanoptimal** [comment]
Does this page answer your question?

http://ejml.org/wiki/index.php?title=Solving_Linear_Systems
