### ISSUE TITLE
How to perform row-wise sum efficiently on sparse matrices?

### ISSUE THREAD

**Issue by szarnyasg** [lessthanoptimal/ejml#49]
Our use case needs to perform row-wise sum on sparse matrix elements. We tried two approaches:

1. Given an `n × m` input matrix `input`, one way to approach is to initialize a vector of length `m` filled with 1 values and multiply the matrix with it, resulting in vector `output` of length `n` containing the sums:

    ```java
        SimpleMatrix ones = new SimpleMatrix(input.getNumCols(), 1);
        ones.fill(1);
        CommonOps_DSCC.mult(input, ones.getMatrix(), output);
    ```

2. Iterate through the non-zero elements:

    ```java
        for (int col = 0; col < input.numCols; col++) {
            int idx0 = input.col_idx[col];
            int idx1 = input.col_idx[col+1];

            for (int i = idx0; i < idx1; i++) {
                int row = input.nz_rows[i];
                double value = input.nz_values[i];

                output.add(row, 0, value);
            }
        }
    ```

I created an [example test method](https://github.com/szarnyasg/sparse-matrix-benchmarks/blob/master/src/test/java/benchmarks/EjmlTest.java) to reproduce this.

When executed with 10,000 runs (spec: Oracle JDK8 / Ubuntu 18.04 and an Intel 2760QM CPU), it needs 24 ms for approach #1, but only 9 ms for approach #2. The difference is not huge, but maybe there is an even faster way to perform this.

**Comment by lessthanoptimal** [comment]
Since dense matrices had the row sum and sparse didn't I added that function and several other related row/column ops. Plus you doing that weird stuff with simple matrix pointed out that there was no sparse fill operation. New code is in the latest snapshot.

I took a quick look at your benchmark You might want to consider using JMH http://openjdk.java.net/projects/code-tools/jmh/.  With the JVM past history will affect future results. So depending on which operation you run first you can get different benchmark results. JMH takes care of all of that.

If in your use case you can predeclare memory and reuse it you should. Less the garbage collector runs the faster your application will be.

P.S. I'm not normally THIS quick in responding/updating code.

**Comment by lessthanoptimal** [comment]
P.S. on my computer method 2 took 5ms and my code took 4ms. I ran the test a few times.

**Comment by szarnyasg** [comment]
> P.S. I'm not normally THIS quick in responding/updating code.
This was quick indeed. Thank you, it is much appreciated.

We'll report back on how much these changes sped up our calculations.

**Comment by lessthanoptimal** [comment]
it's in the current stable release.
