### ISSUE TITLE
`multTransA` slower than `mult` for `DMatrixSparseCSC`?

### ISSUE THREAD

**Issue by FlorentinD** [lessthanoptimal/ejml#85]
To my understanding, it should be ideal, if for `AxB` the matrix `A` is transposed and both are stored in CSC.
However, benchmarks showed, that `multTransA` is actually **much slower** than `mult`.

Maybe there could be heuristic, that decides whether a column should be made dense for the computation (based on the sparsity of the column).

Benchmark:
```
public class MxMBenchmark extends MxMBaseBenchmark {

    DMatrixSparseCSC matrix;
    DMatrixSparseCSC transposedMatrix;

    @Param({"100000"})
    private int dimension;

    @Param({"200000"})
    private int elementCount;

    @Setup
    public void setup() {
        matrix = RandomMatrices_DSCC.rectangle(dimension, dimension, elementCount, new Random(42));
        transposedMatrix = CommonOps_DSCC.transpose(matrix, null, null);
    }

    @Benchmark
    public void mxm(Blackhole bh) {
        CommonOps_DSCC.mult(matrix, matrix, result);
        bh.consume(result);
    }

    @Benchmark
    public void mTxm(Blackhole bh) {
        bh.consume(CommonOps_DSCC.multTransA(transposedMatrix, matrix, null, null, null));
    }
```

Results:
```
Benchmark                       (dimension)  (elementCount)  Mode  Cnt      Score     Error  Units
ejmlOps.mult.MxMBenchmark.mTxm       100000          200000  avgt    5  14493.829 ± 941.827  ms/op
ejmlOps.mult.MxMBenchmark.mxm        100000          200000  avgt    5      4.908 ±   1.111  ms/op
```

**Comment by FlorentinD** [comment]
@lessthanoptimal Am I missing something/Would you expect this behavior?

**Comment by FlorentinD** [comment]
Also if the difference is that high, it might be faster to first transpose and then use the normal `mult`.
If I saw it correctly, thats also what f.i. is done in https://github.com/DrTimothyAldenDavis/SuiteSparse/tree/master/GraphBLAS

**Comment by lessthanoptimal** [comment]
I'll go over it this weekend. I do remember benchmarking these operations and deciding to leave out at least one variant of mult trans (A,B) because I couldn't figure out a way to make it run fast.

**Comment by FlorentinD** [comment]
You didn't implement `multTransAB` for A and B being in CSC format.
The same behaviour can be seen for `multTransB`. However there I expected it to be slower.
Maybe its always faster to just transpose the matrix and than use the normal `mult` (of course with the drawback of additional space being needed).

**Comment by FlorentinD** [comment]
Thank you for looking into this!

**Comment by lessthanoptimal** [comment]
Didn't get to it this weekend since I attempted to finish the concurrency update. I'm shooting to go over it this week.

**Comment by lessthanoptimal** [comment]
So I'm looking are your code. Try passing in non-null values for the work space and re-use it. Basically declare it as a class field and not a local variable. I bet it speeds up a lot.

**Comment by lessthanoptimal** [comment]
Just tried that myself. It didn't help. I am a bit surprised how drastic the slow down is.

**Comment by FlorentinD** [comment]
Reassuring for me, that my intuition wasn't completely off here.
Do you have a resource for your current implementation?
I wasn't really successful to find algorithms for transposed sparse multiply of CSR/CSC matrices.

**Comment by lessthanoptimal** [comment]
Yeah it's not standard for sparse matrices. It was an addition I came up with along with a few others after the first pass and I apparently didn't test it on large enough matrices. The good news is that I have root caused the issue. There's a flaw in the algorithm where it's runtime complexity is dependent on the shape. It's O(N^2) instead of O(N) like `mult()`. For dense matrices A^T*B is very fast to compute. I've not figured out a good trick to avoid exhaustively going through all the columns a second time. I probably need to re-order the indexes multiplication is done in.

**Comment by lessthanoptimal** [comment]
After going over it more carefully I think it's unlikely to have an O(N) algorithm which doesn't involve transposing one matrix. There are only fast look ups along columns. You need to be able to traverse through the columns of one matrix, get the list of rows, then those rows need to correspond to the columns in the other matrix. That happens for `A*B` and `A^t*B^t`, but not the other permutations. Unless I'm missing something `multTransA` and `multTransB` should probably be removed. For `multTransAB` that probably won't work since it lends itself towards constructing a fast row-major matrix, when CSC is column major. Well I suppose that's not useless I just can't think of a time I've ever needed to compute `C^t = (A^t * B^t)^t`. Tempted to code it up just because.

**Comment by FlorentinD** [comment]
Your conclusion would match with the implementation in the above mentioned `GraphBLAS` library in C.
Interesting that there seems to be no literature about.

So deprecating/removing `multTransA` and `multTransB` will be the way to go then?

**Comment by lessthanoptimal** [comment]
I've found another case of this same problem. I'm going to explore a custom transpose which would not flip the values just the indexes. That should reduce memory and speed things up a little bit.

**Comment by lessthanoptimal** [comment]
Ended up removing the functions and updated code which used them. Most of the time that resulted in a significant speed up. Thanks for pointing this out. DSCC is also going to have the full JHM treatment before the next release.
